import { supabase, requireRole, uploadImage } from "./supabase.js";
const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const profile=await requireRole("admin");
if(profile){
  document.body.classList.add("admin-ready");
  document.querySelectorAll(".side").forEach(btn=>btn.onclick=()=>{document.querySelectorAll(".side,.admin-section").forEach(el=>el.classList.remove("active"));btn.classList.add("active");document.querySelector(`#${btn.dataset.section}`).classList.add("active")});
  document.querySelector("#logout").onclick=async()=>{await supabase.auth.signOut();location.href="index.html"};
  const setMessage=(id,text,ok=false)=>{const el=document.querySelector(id);el.textContent=text;el.style.color=ok?"var(--green)":"var(--red)"};
  async function loadLocation(){const{data}=await supabase.from("house_settings").select("*").eq("id",1).maybeSingle();if(data){document.querySelector("#location-title").value=data.title||"";document.querySelector("#location-address").value=data.address||"";document.querySelector("#location-directions").value=data.directions||"";document.querySelector("#location-maps").value=data.maps_url||""}}
  document.querySelector("#location-form").onsubmit=async e=>{e.preventDefault();try{setMessage("#location-message","Salvando...");const file=document.querySelector("#location-image").files[0];const imageUrl=await uploadImage(file,"location");const payload={id:1,title:document.querySelector("#location-title").value.trim(),address:document.querySelector("#location-address").value.trim(),directions:document.querySelector("#location-directions").value.trim(),maps_url:document.querySelector("#location-maps").value.trim(),updated_at:new Date().toISOString()};if(imageUrl)payload.image_url=imageUrl;const{error}=await supabase.from("house_settings").upsert(payload);if(error)throw error;setMessage("#location-message","Localização atualizada.",true)}catch(err){setMessage("#location-message",err.message)}};
  async function loadMenu(){const{data=[]}=await supabase.from("menu_items").select("*").order("sort_order");document.querySelector("#menu-admin-list").innerHTML=data.map(x=>`<article class="list-item">${x.image_url?`<img src="${esc(x.image_url)}" alt="">`:"<span></span>"}<div><h3>${esc(x.name)}</h3><p>${esc(x.description||"")}</p></div><div class="card-actions"><button class="btn alt edit-menu" data-id="${x.id}">Editar</button><button class="btn danger delete-menu" data-id="${x.id}">Excluir</button></div></article>`).join("");document.querySelectorAll(".edit-menu").forEach(b=>b.onclick=()=>{const x=data.find(i=>i.id===b.dataset.id);document.querySelector("#menu-id").value=x.id;document.querySelector("#menu-name").value=x.name;document.querySelector("#menu-description").value=x.description||"";document.querySelector("#menu-price").value=x.price??"";document.querySelector("#menu-order").value=x.sort_order||0;scrollTo({top:0,behavior:"smooth"})});document.querySelectorAll(".delete-menu").forEach(b=>b.onclick=async()=>{if(confirm("Excluir este item?")){await supabase.from("menu_items").delete().eq("id",b.dataset.id);loadMenu()}})}
  document.querySelector("#menu-form").onsubmit=async e=>{e.preventDefault();try{setMessage("#menu-message","Salvando...");const id=document.querySelector("#menu-id").value;const imageUrl=await uploadImage(document.querySelector("#menu-image").files[0],"menu");const payload={name:document.querySelector("#menu-name").value.trim(),description:document.querySelector("#menu-description").value.trim(),price:document.querySelector("#menu-price").value||null,sort_order:Number(document.querySelector("#menu-order").value)||0,active:true};if(id)payload.id=id;if(imageUrl)payload.image_url=imageUrl;const{error}=await supabase.from("menu_items").upsert(payload);if(error)throw error;e.target.reset();document.querySelector("#menu-id").value="";setMessage("#menu-message","Item salvo.",true);loadMenu()}catch(err){setMessage("#menu-message",err.message)}};
  async function loadPlaces(){const{data=[]}=await supabase.from("eateries").select("*").order("sort_order");document.querySelector("#places-admin-list").innerHTML=data.map(x=>`<article class="list-item">${x.image_url?`<img src="${esc(x.image_url)}" alt="">`:"<span></span>"}<div><h3>${esc(x.name)}</h3><p>${esc(x.description||"")}</p></div><div class="card-actions"><button class="btn alt edit-place" data-id="${x.id}">Editar</button><button class="btn danger delete-place" data-id="${x.id}">Excluir</button></div></article>`).join("");document.querySelectorAll(".edit-place").forEach(b=>b.onclick=()=>{const x=data.find(i=>i.id===b.dataset.id);document.querySelector("#place-id").value=x.id;document.querySelector("#place-name").value=x.name;document.querySelector("#place-description").value=x.description||"";document.querySelector("#place-maps").value=x.maps_url||"";document.querySelector("#place-order").value=x.sort_order||0;scrollTo({top:0,behavior:"smooth"})});document.querySelectorAll(".delete-place").forEach(b=>b.onclick=async()=>{if(confirm("Excluir este local?")){await supabase.from("eateries").delete().eq("id",b.dataset.id);loadPlaces()}})}
  document.querySelector("#place-form").onsubmit=async e=>{e.preventDefault();try{setMessage("#place-message","Salvando...");const id=document.querySelector("#place-id").value;const imageUrl=await uploadImage(document.querySelector("#place-image").files[0],"places");const payload={name:document.querySelector("#place-name").value.trim(),description:document.querySelector("#place-description").value.trim(),maps_url:document.querySelector("#place-maps").value.trim(),sort_order:Number(document.querySelector("#place-order").value)||0,active:true};if(id)payload.id=id;if(imageUrl)payload.image_url=imageUrl;const{error}=await supabase.from("eateries").upsert(payload);if(error)throw error;e.target.reset();document.querySelector("#place-id").value="";setMessage("#place-message","Local salvo.",true);loadPlaces()}catch(err){setMessage("#place-message",err.message)}};
  await Promise.all([loadLocation(),loadMenu(),loadPlaces()]);
}
